#!/bin/bash

display_info() {
    domain="$1"
    subdomain="$2"
    record_type=$(dig +short -t CNAME "$subdomain.$domain" | awk '{print $1}')
    destination=$(dig +short "$subdomain.$domain")

    if [ -n "$destination" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "The subdomain $subdomain does not exist or has no DNS records"
    fi
}

domain="$1"
subdomain="$2"

if [ -z "$domain" ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

if [ -z "$subdomain" ]; then
    display_info "$domain" www
    display_info "$domain" lb-01
    display_info "$domain" web-01
    display_info "$domain" web-02
else
    display_info "$domain" "$subdomain"
fi
