#!/usr/bin/env bash
# Install nginx web server

sudo apt-get  update;
sudo apt-get  install -y nginx;
sudo ufw allow 'Nginx HTTP';
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';

sudo service nginx start;
