#!/usr/bin/env bash
# Script that configures an Nginx server so /redirect_me redirects to another page
# Install Nginx
apt-get update
apt-get -y install nginx

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    root /var/www/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart
