#!/usr/bin/env bash
# Script that configures an Nginx server to handle a custom 404 pagex
apt-get update
apt-get -y install nginx

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    root /usr/share/nginx/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default
service nginx restart
